"use client";
import { useMemo, useState } from "react";
import { Plus, X } from "lucide-react";
import { useStore } from "@/lib/store";
import { SETUPS, SOURCES, type JournalEntry } from "@/lib/types";
import { Badge, Card, Field, Input, PageHeader, Select, SectionTitle, Textarea } from "../ui";
const blank=():JournalEntry=>({id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10),ticker:"",direction:"Long",tradeType:"Daytrade",setup:SETUPS[0],trafficLight:"yellow",entry:0,exit:0,initialStop:0,positionSize:0,pnl:0,rMultiple:0,ruleCompliant:true,source:SOURCES[0],emotion:"",mistake:"",lesson:""});
const grade=(j:JournalEntry)=>`${j.ruleCompliant?"Guter":"Schlechter"} Trade / ${j.pnl>=0?"gutes":"schlechtes"} Ergebnis`;
export function JournalView(){const {data,addJournal}=useStore();const [entry,setEntry]=useState<JournalEntry|null>(null);const stats=useMemo(()=>{const real=data.journal.filter(j=>!j.demo);return {count:real.length,pnl:real.reduce((a,j)=>a+j.pnl,0),r:real.length?real.reduce((a,j)=>a+j.rMultiple,0)/real.length:0,compliance:real.length?real.filter(j=>j.ruleCompliant).length/real.length*100:0}},[data.journal]);const calc=(next:JournalEntry)=>{const unit=Math.abs(next.entry-next.initialStop);return {...next,pnl:Number(((next.exit-next.entry)*(next.direction==="Long"?1:-1)*next.positionSize).toFixed(2)),r:unit?Number((((next.exit-next.entry)*(next.direction==="Long"?1:-1))/unit).toFixed(2)):0}};const set=<K extends keyof JournalEntry>(k:K,v:JournalEntry[K])=>setEntry(e=>e?calc({...e,[k]:v}):e);const save=(e:React.FormEvent)=>{e.preventDefault();if(entry){addJournal(entry);setEntry(null)}};return <div className="page"><PageHeader eyebrow="FEEDBACK LOOP" title="Journal" description="Prozessqualität sichtbar machen – unabhängig vom einzelnen Ergebnis." action={<button className="primary compact" onClick={()=>setEntry(blank())}><Plus size={17}/> Trade</button>}/><div className="stats-row"><Card><span>Trades</span><strong>{stats.count}</strong></Card><Card><span>Gesamt-P&amp;L</span><strong className={stats.pnl>=0?"positive":"negative"}>${stats.pnl.toFixed(2)}</strong></Card><Card><span>Ø Ergebnis</span><strong>{stats.r.toFixed(2)} R</strong></Card><Card><span>Regelkonform</span><strong>{stats.compliance.toFixed(0)}%</strong></Card></div><Card><SectionTitle meta={`${data.journal.length} Einträge`}>Trade-Historie</SectionTitle><div className="journal-table"><div className="table-head"><span>Trade</span><span>Setup</span><span>Bewertung</span><span>Ergebnis</span></div>{data.journal.map(j=><div key={j.id}><div><strong>{j.ticker}</strong><small>{new Date(j.date+"T12:00").toLocaleDateString("de-DE")} · {j.direction}</small></div><span>{j.setup}</span><span><Badge tone={j.ruleCompliant?(j.pnl>=0?"green":"blue"):(j.pnl>=0?"yellow":"red")}>{grade(j)}</Badge></span><div className="align-right"><strong className={j.pnl>=0?"positive":"negative"}>{j.pnl>=0?"+":""}${j.pnl.toFixed(2)}</strong><small>{j.rMultiple} R</small></div></div>)}</div></Card>
{entry&&<div className="modal-backdrop" onMouseDown={()=>setEntry(null)}><form className="modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">JOURNAL</span><h2>Trade dokumentieren</h2></div><button type="button" className="icon-button" onClick={()=>setEntry(null)}><X/></button></div><div className="form-grid two"><Field label="Datum"><Input type="date" value={entry.date} onChange={e=>set("date",e.target.value)}/></Field><Field label="Ticker *"><Input required value={entry.ticker} onChange={e=>set("ticker",e.target.value.toUpperCase())}/></Field><Field label="Richtung"><Select value={entry.direction} onChange={e=>set("direction",e.target.value as JournalEntry["direction"])}><option>Long</option><option>Short</option></Select></Field><Field label="Trade-Typ"><Select value={entry.tradeType} onChange={e=>set("tradeType",e.target.value as JournalEntry["tradeType"])}><option>Daytrade</option><option>Swing</option><option>Day-to-Swing</option></Select></Field><Field label="Setup"><Select value={entry.setup} onChange={e=>set("setup",e.target.value)}>{SETUPS.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Marktampel"><Select value={entry.trafficLight} onChange={e=>set("trafficLight",e.target.value as JournalEntry["trafficLight"])}><option value="green">Grün</option><option value="yellow">Gelb</option><option value="red">Rot</option></Select></Field>{(["entry","exit","initialStop","positionSize"] as const).map(k=><Field key={k} label={{entry:"Entry",exit:"Exit",initialStop:"Initialstop",positionSize:"Positionsgröße"}[k]}><Input type="number" step="0.01" value={entry[k]} onChange={e=>set(k,Number(e.target.value))}/></Field>)}<Field label="Quelle"><Select value={entry.source} onChange={e=>set("source",e.target.value)}>{SOURCES.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Emotion"><Input value={entry.emotion} onChange={e=>set("emotion",e.target.value)}/></Field></div><label className="toggle-line"><input type="checkbox" checked={entry.ruleCompliant} onChange={e=>set("ruleCompliant",e.target.checked)}/> Regelkonform gehandelt</label><div className="computed-result"><span>Automatisch berechnet</span><strong className={entry.pnl>=0?"positive":"negative"}>{entry.pnl.toFixed(2)} USD · {entry.rMultiple} R</strong></div><Field label="Fehler"><Textarea rows={2} value={entry.mistake} onChange={e=>set("mistake",e.target.value)}/></Field><Field label="Erkenntnis"><Textarea rows={2} value={entry.lesson} onChange={e=>set("lesson",e.target.value)}/></Field><Field label="Screenshot-Platzhalter" hint="Lokale Bildspeicherung folgt in einer späteren Version."><Input disabled value="Noch nicht verfügbar"/></Field><button className="primary full">Journal-Eintrag speichern</button></form></div>}</div>}

