"use client";
import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Info, ShieldCheck } from "lucide-react";
import { calculateOrb, type OrbInput } from "@/lib/orb";
import { Badge, Card, Field, Input, PageHeader, SectionTitle } from "../ui";
const initial:OrbInput={entry:103,lowOfDay:100,adr:6,riskBudget:300,first30MinutesComplete:true,candleClosedAboveRange:true,requirePriorDayHigh:false,priorDayHighExceeded:false};
const euro=(n:number)=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"USD"}).format(n);
export function OrbView(){const [input,setInput]=useState(initial);const result=useMemo(()=>calculateOrb(input),[input]);const set=(key:keyof OrbInput,value:number|boolean)=>setInput(v=>({...v,[key]:value}));return <div className="page"><PageHeader eyebrow="PLANUNG · KEINE ORDER" title="ORB Assistant" description="30-Minuten Opening Range Breakout strukturiert prüfen und Risiko planen." action={<Badge tone="yellow">REGELN VORLÄUFIG</Badge>}/>
<div className="orb-layout"><div className="stack"><Card><SectionTitle>Pre-Trade Check</SectionTitle><div className="check-stack"><label><input type="checkbox" checked={input.first30MinutesComplete} onChange={e=>set("first30MinutesComplete",e.target.checked)}/><span><strong>Erste 30 Minuten beendet</strong><small>Opening Range ist vollständig.</small></span></label><label><input type="checkbox" checked={input.candleClosedAboveRange} onChange={e=>set("candleClosedAboveRange",e.target.checked)}/><span><strong>5-Min-Kerze über OR-High geschlossen</strong><small>Ein Wick allein ist kein Entry-Signal.</small></span></label><label><input type="checkbox" checked={input.requirePriorDayHigh} onChange={e=>set("requirePriorDayHigh",e.target.checked)}/><span><strong>Vortageshoch als Pflichtfilter</strong><small>Optionale Regel aktivieren.</small></span></label>{input.requirePriorDayHigh&&<label className="nested"><input type="checkbox" checked={input.priorDayHighExceeded} onChange={e=>set("priorDayHighExceeded",e.target.checked)}/><span><strong>Vortageshoch überschritten</strong></span></label>}</div></Card><Card><SectionTitle>Preise & Risiko</SectionTitle><div className="form-grid two"><Field label="Entry ($)"><Input type="number" step="0.01" value={input.entry} onChange={e=>set("entry",Number(e.target.value))}/></Field><Field label="Tagestief ($)"><Input type="number" step="0.01" value={input.lowOfDay} onChange={e=>set("lowOfDay",Number(e.target.value))}/></Field><Field label="ADR in Dollar"><Input type="number" min="0" step="0.01" value={input.adr} onChange={e=>set("adr",Number(e.target.value))}/></Field><Field label="Max. Gesamtrisiko ($)"><Input type="number" min="0" step="1" value={input.riskBudget} onChange={e=>set("riskBudget",Number(e.target.value))}/></Field></div><div className="info-line"><Info size={15}/> Relatives Volumen ist ein Qualitätskriterium, wird im MVP aber noch nicht berechnet.</div></Card></div>
<div className="stack"><Card className={`orb-verdict ${result.valid?"valid":"invalid"}`}><div className="verdict-icon">{result.valid?<CheckCircle2/>:<AlertTriangle/>}</div><div><span className="overline">STATUS</span><h2>{result.valid?"Setup gültig":"Kein Trade"}</h2><p>{result.valid?"Alle erfassten Pflichtkriterien sind erfüllt.":result.reasons[0]}</p></div></Card><Card><SectionTitle>Distanzcheck</SectionTitle><div className="metrics-grid"><div><span>LoD-Distanz</span><strong>{euro(result.distance)}</strong></div><div><span>% der ADR</span><strong>{result.distancePercentAdr}%</strong></div><div><span>Gew. Risiko/Aktie</span><strong>{euro(result.weightedRiskPerShare)}</strong></div><div><span>Gesamtstückzahl</span><strong>{result.totalShares}</strong></div></div><div className="adr-meter"><span style={{width:`${Math.min(result.distancePercentAdr,100)}%`}}/><i style={{left:"66%"}}>66 %</i></div></Card><Card><SectionTitle>Drei Stop-Tranchen</SectionTitle><div className="tranche-table"><div className="table-head"><span>Tranche</span><span>Stop</span><span>Risiko/Aktie</span><span>Stück</span></div>{result.stops.map((stop,i)=><div key={stop}><strong>{i+1}/3</strong><span>{euro(stop)}</span><span>{euro(result.risksPerShare[i])}</span><span>{result.sharesPerTranche[i]}</span></div>)}</div><div className="total-risk"><span>Geplantes Gesamtrisiko</span><strong>{euro(result.totalRisk)}</strong></div></Card>{!result.valid&&<Card className="reasons"><SectionTitle>Warum nicht?</SectionTitle>{result.reasons.map(r=><p key={r}><AlertTriangle size={15}/>{r}</p>)}</Card>}<div className="disclaimer"><ShieldCheck size={15}/> Berechnungshilfe, keine Orderausführung oder Empfehlung.</div></div></div></div>}

