"use client";
import { useMemo, useState } from "react";
import { Check, ClipboardPaste, Copy, Star, Trash2 } from "lucide-react";
import { useStore } from "@/lib/store";
import { SOURCES, type Candidate, type CandidateList, type Direction } from "@/lib/types";
import { Badge, Card, Field, PageHeader, Select, Textarea } from "../ui";
const parse=(raw:string)=>[...new Set(raw.toUpperCase().split(/[\s,;]+/).map(t=>t.replace(/[^A-Z0-9.\-]/g,"")).filter(Boolean))];
export function ScanView(){
 const {data,setCandidates}=useStore(); const [raw,setRaw]=useState(""); const [source,setSource]=useState<string>(SOURCES[0]); const [inbox,setInbox]=useState<string[]>([]); const [notice,setNotice]=useState("");
 const known=useMemo(()=>new Set(data.candidates.map(c=>c.ticker)),[data.candidates]);
 const ingest=()=>{const found=parse(raw);setInbox([...new Set([...inbox,...found])]);setRaw("");setNotice(`${found.length} Ticker erkannt`)};
 const move=(ticker:string,list:CandidateList,direction:Direction,topDog=false)=>{const existing=data.candidates.find(c=>c.ticker===ticker);if(existing)setCandidates(data.candidates.map(c=>c.ticker===ticker?{...c,list,direction,topDog:c.topDog||topDog||list==="top-dogs",source}:c));else {const item:Candidate={id:crypto.randomUUID(),ticker,company:"",direction,list,topDog:topDog||list==="top-dogs",shortLeader:false,status:"aktiv",sector:"",group:"",theme:"",setup:"",source,fundamentals:"",earningsDate:"",trigger:null,entry:null,stop:null,tradingViewUrl:`https://www.tradingview.com/chart/?symbol=${ticker}`,note:""};setCandidates([...data.candidates,item])}setInbox(inbox.filter(t=>t!==ticker))};
 const exportList=async()=>{const text=data.candidates.filter(c=>c.list!=="stock").map(c=>c.ticker).join(",");await navigator.clipboard.writeText(text);setNotice("TradingView-Liste kopiert")};
 return <div className="page"><PageHeader eyebrow="SCHNELLE TRIAGE" title="Scan Inbox" description="Rohe Scan-Ergebnisse einfügen und direkt in deinen Watchlisten-Prozess einsortieren." action={<button className="secondary compact" onClick={exportList}><Copy size={16}/> Listen exportieren</button>}/>
 <div className="scan-layout"><Card><div className="paste-icon"><ClipboardPaste/></div><Field label="Ticker einfügen" hint="Kommas, Leerzeichen und Zeilenumbrüche werden akzeptiert. Duplikate entfernt."><Textarea rows={8} value={raw} onChange={e=>setRaw(e.target.value)} placeholder={"NVDA, META, PLTR\nXLE  TSLA"}/></Field><Field label="Quelle"><Select value={source} onChange={e=>setSource(e.target.value)}>{SOURCES.map(x=><option key={x}>{x}</option>)}</Select></Field><button className="primary full" disabled={!raw.trim()} onClick={ingest}>Ticker übernehmen</button>{notice&&<div className="toast-inline"><Check size={15}/>{notice}</div>}</Card>
 <div className="stack"><div className="section-title outside"><h2>Zu bearbeiten</h2><span>{inbox.length} Ticker</span></div>{inbox.map(t=><Card className="inbox-row" key={t}><div><strong>{t}</strong>{known.has(t)&&<Badge>bereits vorhanden</Badge>}<small>{source}</small></div><div className="inbox-actions"><button onClick={()=>move(t,"bulls-nord","Long")}>Bulls Nord</button><button onClick={()=>move(t,"stalkers","Long")}>Stalkers</button><button onClick={()=>move(t,"fast-ready","Long")}>Fast Ready</button><button onClick={()=>move(t,"watch-long","Long")}>W Long</button><button onClick={()=>move(t,"watch-short","Short")}>W Short</button><button title="Top Dogs" onClick={()=>move(t,"top-dogs","Long",true)}><Star size={16}/> Top</button><button className="focus" onClick={()=>move(t,"focus-long","Long")}>F Long</button><button className="focus short" onClick={()=>move(t,"focus-short","Short")}>F Short</button><button title="Verwerfen" onClick={()=>setInbox(inbox.filter(x=>x!==t))}><Trash2 size={16}/></button></div></Card>)}{!inbox.length&&<div className="empty big"><ClipboardPaste size={28}/><strong>Inbox ist leer</strong><span>Füge links oder oben neue Scan-Ergebnisse ein.</span></div>}</div></div></div>;
}
